require('core.options')
require('core.keymaps')
require('core.plugins')
require('core.colorscheme')
require('core.cmp')

require('addon.lsp')
require('addon.autopairs')
require('addon.telescope')
require('addon.treesitter')
